name: build and push pdf

on:
  push:
    branches: [ "trunk" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Typst Compiler
        uses: ammar-ahmed22/compile-typst-action@v1.0.2
        with:
          source_paths: './*.typ'
          output_paths: 'dist/'
